spring:
  application:
    name: user-service
  kafka:
    bootstrap-servers: 172.16.40.124:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8081
